#!/bin/sh
set -e
CAMUNDA_PWD=`pwgen -n1 8`
echo "=========\n\nYOUR CAMUNDA PASSWORD IS\n${CAMUNDA_PWD}\n\n========="
JAVA_OPTS="${JAVA_OPTS} -Dcamunda.bpm.admin-user.password=$CAMUNDA_PWD"
sh -c "$1"
